### ISSUE TITLE
firewall reconcile reports succeeded:false, but cluster reconciliation is reported as successful

### ISSUE THREAD

**Issue by mwennrich** [metal-stack/gardener-extension-provider-metal#245]
After changing firewall spec, gepm reports succeeded: false

```
{"level":"info","ts":"2022-03-31T06:16:24.652Z","logger":"infrastructure_controller","msg":"Ensuring finalizer","infrastructure":"shoot--pz9cjf--mwen-fel/mwen-fel","operation":"reconcile"}
{"level":"info","ts":"2022-03-31T06:16:24.693Z","logger":"infrastructure_controller","msg":"Reconciling the infrastructure","namespace":"shoot--pz9cjf--mwen-fel","name":"mwen-fel"}
{"level":"info","ts":"2022-03-31T06:16:24.823Z","logger":"infrastructure-actuator","msg":"firewall creation in progress","cluster-id":"0c2127f6-4bd2-46be-85f3-2b2b86d36e96","cluster":"mwen-fel","succeeded":false}
{"level":"info","ts":"2022-03-31T06:16:24.847Z","logger":"infrastructure_controller","msg":"Successfully reconciled infrastructure","namespace":"shoot--pz9cjf--mwen-fel","name":"mwen-fel"}
```

==> `succeeded":false`

Spec has correct new parameters (size, image):

```
kind: Infrastructure
metadata:
  annotations:
    gardener.cloud/timestamp: 2022-03-31 06:16:24.604946862 +0000 UTC
  creationTimestamp: "2022-03-10T12:12:34Z"
  name: mwen-fel
spec:
  providerConfig:
    apiVersion: metal.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureConfig
    firewall:
      image: firewall-ubuntu-2.0.20220315
      size: c1-xlarge-x86
status:
  lastOperation:
    description: Successfully reconciled infrastructure
    lastUpdateTime: "2022-03-31T06:16:24Z"
    progress: 100
    state: Succeeded
    type: Reconcile
  providerStatus:
    apiVersion: metal.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureStatus
    firewall:
      machineID: metal:///fel-wps101/ef113e00-e3d3-11e9-8000-3cecef22b292
      succeeded: false
```

Machine is still the old one:

```
$ metalctl machine ls --id ef113e00-e3d3-11e9-8000-3cecef22b292
ID                                                      LAST EVENT      WHEN    AGE             HOSTNAME                        PROJECT                                 SIZE            IMAGE                           PARTITION  
ef113e00-e3d3-11e9-8000-3cecef22b292                    Phoned Home     17s     183d 16h        shoot--pz9cj...-firewall-5bdcb  2c83b020-aa03-4535-8978-6676b0491584    n1-medium-x86   Firewall 2 Ubuntu 20210912      fel-wps101
```

But cluster is reported as successfully reconciled to the user:

```plaintext
UID                                     NAME            VERSION       OPERATION       PROGRESS                API     CONTROL NODES   SYSTEM  SIZE    AGE             PURPOSE
0c2127f6-4bd2-46be-85f3-2b2b86d36e96    mwen-fel        1.21.11↑      Succeeded       100% [Reconcile]        True    True    True    True    2≤2≤3   406d 17h        eval
```

shoot status:

```
Status:
  Cluster Identity:  shoot--pz9cjf--mwen-fel-0c2127f6-4bd2-46be-85f3-2b2b86d36e96-gardener-soil-prod
  Conditions:
    Last Transition Time:  2022-03-31T06:16:50Z
    Last Update Time:      2022-03-31T06:16:49Z
    Message:               API server /healthz endpoint responded with success status code.
    Reason:                HealthzRequestSucceeded
    Status:                True
    Type:                  APIServerAvailable
    Last Transition Time:  2022-03-31T06:16:50Z
    Last Update Time:      2022-03-31T06:16:49Z
    Message:               All control plane components are healthy.
    Reason:                ControlPlaneRunning
    Status:                True
    Type:                  ControlPlaneHealthy
    Last Transition Time:  2022-03-31T06:16:50Z
    Last Update Time:      2022-03-31T06:16:49Z
    Message:               All nodes are ready.
    Reason:                EveryNodeReady
    Status:                True
    Type:                  EveryNodeReady
    Last Transition Time:  2022-03-31T06:16:50Z
    Last Update Time:      2022-03-31T06:16:49Z
    Message:               All system components are healthy.
    Reason:                SystemComponentsRunning
    Status:                True
    Type:                  SystemComponentsHealthy
  Constraints:
    Last Transition Time:  2022-03-31T06:16:50Z
    Last Update Time:      2022-03-28T00:01:47Z
    Message:               All webhooks are properly configured.
    Reason:                NoProblematicWebhooks
    Status:                True
    Type:                  HibernationPossible
    Last Transition Time:  2022-03-31T06:16:50Z
    Last Update Time:      2022-03-28T00:01:47Z
    Message:               All webhooks are properly configured.
    Reason:                NoProblematicWebhooks
    Status:                True
    Type:                  MaintenancePreconditionsSatisfied
  Gardener:
    Id:        48a2253ace11a615e09773106116899d3020bb61fae0f7a3575b899bd1772ee3
    Name:      gardenlet-65b7cf8745-7s4sr
    Version:   v1.26.3
  Hibernated:  false
  Last Operation:
    Description:        Shoot cluster state has been successfully reconciled.
    Last Update Time:   2022-03-31T06:16:49Z
    Progress:           100
    State:              Succeeded
    Type:               Reconcile
  Observed Generation:  727
  Seed Name:            felwps101b
  Technical ID:         shoot--pz9cjf--mwen-fel
  UID:                  0c2127f6-4bd2-46be-85f3-2b2b86d36e96
```
